In [8]:
import numpy as np

m1 = np.matrix('0.7 0.3; 0.3 0.7')
m2 = np.matrix('1 0; 0 1')
#print(np.linalg.matrix_power(m1,100))
#print(np.matmul(m1,m2))
m3 = np.matrix('0.4 0.4 0.2; 0.4 0.6 0; 0.4 0 0.6')
#m4 = np.matrix('0.4 0.2 0.2 0.1 0.1; 0.4 0.3 0.3 0 0; 0.4 0 0.6')

print(np.linalg.matrix_power(m3,100))


[[0.4 0.4 0.2]
 [0.4 0.4 0.2]
 [0.4 0.4 0.2]]
